### ISSUE TITLE
C# Language Support (.NET Core or Mono)

### ISSUE THREAD

**Issue by bruxisma** [ixm-one/ixm#1]
Currently, CMake only supports C# when using Visual Studio. I would much prefer the ability to use something like [.NET Core][1] or [Mono][2]. This support might include acquiring NuGet dependencies, linking the C# Runtime used to a C or C++ project, or simply building a few components as part of a larger project. We do not *yet* know the exact behavior. This will be determined as we attempt to implement initial support.

## TODO

- [ ] .NET Core 
   - [ ] Detection
   - [ ] Compiling
   - [ ] Linking
   - [ ] Native Integration
- [ ] Mono
  - [ ] Detection
  - [ ] Compiling
  - [ ] Linking
  - [ ] Native Integration

[1]: https://docs.microsoft.com/en-us/dotnet/core/about
[2]: https://www.mono-project.com/docs/

**Comment by slurps-mad-rips** [comment]
See #3 for comment. Custom language support is going to have to be something IXM does on its own because CMake is incapable of being well designed, well thought out, or even having the foresight to be usable in the first place. In case it isn't obvious: I despise this tool and the sooner I can get IXM out the door to fix a lot of the problems with it, the better.

**Comment by bruxisma** [comment]
Closing, as this project has burned me out, and I cannot continue working on it in its current state. CMake has changed massively since this project was started. Most of it is no longer necessary. A new repository will be launched in September.
