### ISSUE TITLE
New bootstrap script causes severe execution failure

### ISSUE THREAD

**Issue by bruxisma** [ixm-one/ixm#37]
This is now possible because we generate a bootstrap script that pulls IXM down via git behind the scenes so that it will automatically update as needed. This causes TONS of incorrect output and lots of failure. For example:

1) Color output doesn't work (but does if IXM is manually set on the command line *or* is used instead of the bootstrap script)
2) aspect() calls fail (due to how they are implemented)
3) Just a full cascade of errors I wasn't expecting.

This NEEDS to be resolved before launch.

**Comment by slurps-mad-rips** [comment]
This turned out to be entirely because of how FetchContent works. We'll be moving the entire infrastructure over to Netlify soon, which means we won't need the `get.ixm.one` site soon, and redirects will "just work". However the bootstrap script to make sure the `URL` call is always up to date under the hood WILL be removed. I'll be filing a feature request upstream for FetchContent to allow doing `GIT <url>` as an alias to `GIT_REPOSITORY` which will help with this issue. 

That said, the "Live at HEAD" approach is going to be dropped in favor of a high-frequency LTS train model (this will be written up and defined soon-ish)

**Comment by bruxisma** [comment]
Closing, as this project has burned me out, and I cannot continue working on it in its current state. CMake has changed massively since this project was started. Most of it is no longer necessary. A new repository will be launched in September.
