### ISSUE TITLE
Rust Language Support

### ISSUE THREAD

**Issue by bruxisma** [ixm-one/ixm#4]
As wonderful as Rust's `cargo` is, not all projects are mono-lingual. It would be extremely great if a C++ or C project could link to an existing Rust project. Even better, being able to build a rust program that is then used for an `add_custom_command` or `add_custom_target` would be fantastic!

- [ ] Toolchain Detection
- [ ] Compiling Native Libraries
- [ ] Cross Compiling Support
- [ ] C and C++ integration
- [ ] Some form of dependency tracking

**Comment by slurps-mad-rips** [comment]
As an update, we cannot add `enable_language` support for Rust. Thus, we need to have some hooks in place to permit calling `find_package(Rust)` to allow building a module into a native static library or something similar. Unfortunately, we'll need CMake native support for Rust otherwise.

On the bright side, we have control over the `project()` command, and thus we can do effectively anything we want within it.

**Comment by slurps-mad-rips** [comment]
After investigating for a bit, we might be able to use the `enable_language` mechanism after all, if we can do what CUDA does and use `CMAKE_LINKER` in some fashion. Unsure how well that'll pan out though :/

**Comment by slurps-mad-rips** [comment]
See comment on #3. The `CMAKE_LINKER` approach does not work in the slightest. It is absolute bullshit and I am tired of dealing with CMake's failings. It is an absolute nightmare and I wish this tool didn't exist in the first place.

**Comment by bruxisma** [comment]
Closing, as this project has burned me out, and I cannot continue working on it in its current state. CMake has changed massively since this project was started. Most of it is no longer necessary. A new repository will be launched in September.
